name: FastBans
version: '${version}'
main: lava.fastbans.FastBans
api-version: '1.20'
author: Lava
description: Advanced ban plugin for minecraft servers
commands:
  ban:
    description: Ban a player
    usage: /<command> <player> [reason] [time]
    permission: fastbans.admin
  unban:
    description: Unban a player
    usage: /<command> <player>
    permission: fastbans.admin